### PR TITLE
Faster parser for CrystFEL stream files

### PR DESCRIPTION
**Pull request by kmdalton**
I wrote a faster version of the stream file parser. It mostly just uses more numpy and less pandas while vectorizing operations within a crystal block.

### CODE REVIEW

**Comment by DHekstra** [comment]
Does this/could this also address https://github.com/rs-station/reciprocalspaceship/issues/213 ?

**Comment by kmdalton** [comment]
@DHekstra ,  i don't know if the information you want is available in the stream file. i would  need to see an example.

**Comment by JBGreisman** [comment]
This looks pretty good to me, but I'll do another look through before approving/merging.

**Comment by kmdalton** [comment]
There are a couple of issues that still need to be addressed
 1) Doeke provided me some more recent stream files, and they seem to break some of my formatting assumptions. 
 2) The current version doesn't respect that some files have the photon energy measured per frame. My code just uses the photon energy in the header for every crystal. This is a problem for XFEL data where the peak energy changes from shot to shot. 

I'm going to hold off until I have a bit more time to look through it.

**Comment by DHekstra** [comment]
@kmdalton, what is the status of this? I'm revisiting some stream files next week, and could test drive your parser.

**Comment by DHekstra** [comment]
that's alright. I have a slow but functional parser.

**Comment by JBGreisman** [comment]
Just checking in here -- is there anything left to do on this PR or should it be merged into main?

**Comment by kmdalton** [comment]
I discovered this version in was incompatible with some stream files provided by @DHekstra. I haven't been able to diagnose the issue yet. I would recommend we hold off on merging.

**Comment by JBGreisman** [comment]
Does this need to be merged anymore? Or will this be superseded by #260 ?

**Pull request closed without merging**
